### ISSUE TITLE
I discover rare great bookmarklet plain text reader mode that delete ads and the hope please of adding google keep and pocket bookmarklets to save our bookmarks and articles easily quickly without heavy synchronization

### ISSUE THREAD

**Issue by trimechee** [thomasleplus/bookmarklets#52]
Hello, thank you so much for these great awesome bookmarklets! Merci beaucoup :) 💯 🥇 

So I have suggestions plesae: google chrome does not have a dark reader mode button that allows us to remove ads, and I found a rare revolutionary bookmarklet that allows us to get the reader mode of a web page by removing ads with a single click!

this plain text bookmarklet is open source, it works perfectly but the source code seems not to have been updated for 6 years, we hope for a fork of this bookmarklet please with the addition of a dark black background to the page for visual comfort, thank you very much!

we also hope please the addition of a google keep bookmarklet so no more need for heavy synchronization or app to save easily our bookmarks and consult them quickly, and also a bookmarklet for pocket (the official bookmarklet on the pocket website no longer works) in order to quickly save our favorite articles, thank you very much!

bookmarklet plain text reader mode bookmarklet : 

javascript:(function()%7Bfunction callback()%7B(function(%24)%7Bvar jQuery%3D%24%3B%24('link%5Brel%3Dstylesheet%5D').add('style').remove()%3B%24('%5Bstyle%5D').attr('style'%2C '')%3B%24('head'). append('<link rel%3D"stylesheet" href%3D"http%3A%2F%2Fmrcoles.com%2Fmedia%2Ftest%2Fmarkdown-css%2Fmarkdown.css" type%3D"text%2Fcss" %2F>')%3B%24('body').addClass('markdown').css(%7Bwidth%3A '600px'%2C margin%3A '2em auto'%2C 'word-wrap'%3A 'break-word'%7D)%3B%24('a img').css(%7B'max-height'%3A '1em'%2C 'max-width'%3A '1em'%7D)%7D)(jQuery.noConflict(true))%7Dvar s%3Ddocument.createElement("script")%3Bs.src%3D"https%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fjquery%2F1.11.1%2Fjquery.min.js"%3Bif(s.addEventListener)%7Bs.addEventListener("load"%2Ccallback%2Cfalse) %7Delse if(s.readyState)%7Bs.onreadystatechange%3Dcallback%7Ddocument.body.appendChild(s)%3B%7D)() 

********************* ************************************************************

https://mrcoles.com/demo/markdown-css/ 

https://github.com/mrcoles/markdown-css?tab=readme-ov-file#bookmarklet 
https://mrcoles.com/bookmarklet/ https://fvsch.com/remarkdown 
https://fvsch.github.io/remarkdown/ https://github.com/fvsch/remarkdown 
https://www.npmjs.com/package/remarkdown.css https://daringfireball.net/projects/markdown/ 

code of plain text bookmarklet:

 $('link[rel=stylesheet]').add('style').remove();
$('[style]').attr('style', '');
$('head').append('<link rel="stylesheet" href="http://mrcoles.com/media/test/markdown-css/markdown.css" type="text/css" />');
$('body').addClass('markdown').css({width: '600px', margin: '2em auto', 'word-wrap': 'break-word'});
$('a img').css({'max-height': '1em', 'max-width': '1em'});
```


### Anything else?

_No response_

**Comment by thomasleplus** [comment]
Hi @trimechee,

My concern with the suggested bookmarklet is that it depends on an external CSS from mrcoles.com. I don't know this website so I don't feel confident to inject it's content inside another page for multiple reason:
- if the site goes down or the URL of the CSS changes, the bookmarklet will stop working.
- if the CSS code is changed later to something malicious, it could become a security concern.

I hope you'll understand.

Cheers,

Tom
